language: node_js

node_js:
  - "0.11"
  - "0.10"

before_install:
  - "curl -o zookeeper-3.4.5.tar.gz http://apache.mirrors.tds.net/zookeeper/zookeeper-3.4.5/zookeeper-3.4.5.tar.gz"
  - "tar -zxf zookeeper-3.4.5.tar.gz"
  - "cp zookeeper-3.4.5/conf/zoo_sample.cfg zookeeper-3.4.5/conf/zoo.cfg"
  - "sudo zookeeper-3.4.5/bin/zkServer.sh start"

notifications:
  email:
    - "jhurliman@jhurliman.org"
